### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Dangdang00** [mi-ri-mo/Ringcafe_8gram#1]
# Navigation Bar

- [ ] sub page navigation bar 수정(현재 margin으로 간격 준 상태)

- [ ] 메뉴 목록 수정(반지카페 홈, 반지카페 소개, 반지팔찌 디자인)

- [ ] ul margin 수정(margin-top, margin-bottom 27로 통일)

- [ ] 선택된 메뉴 글씨 bold

**Comment by Dangdang00** [comment]
# Main Page

- [ ] 명조, Noto Sans 폰트 구분

- [ ] mainBanner Parallax효과 및 아이콘 추가

- [ ] 우리 반지카페 8그램은.. contents 추가

- [ ] 인기 반지팔찌 소개 contents 추가

- [ ] 반지 만드는 방법 가로 스크롤

- [ ] 오시는 길 문구 및 font-size, text-align 수정

**Comment by Dangdang00** [comment]
# About Page

- [ ] 반지, 팔찌 버튼 눌렀을 때 테두리 색 없애기

**Comment by Dangdang00** [comment]
About Page
- [ ] 가격 contents 하단의 반지, 팔찌 이미지, 세로선 세로 정렬(flex 사용)
- [ ] 오시는 길 간격 확인
