### ISSUE TITLE
To-Do List_ver.2

### ISSUE THREAD

**Issue by Dangdang00** [mi-ri-mo/Ringcafe_8gram#2]
- [ ] 722px~767px에서 subBanner 양쪽 이미지 여백

- [ ]  모바일 오시는길 위치, 이용시간, 연락처 가운데 정렬(현재는 왼쪽 정렬)

- [ ] index페이지 Ringcafe8gram 레터링 이미지 추가(세로)
